### ISSUE TITLE
Alternative to custom integration?

### ISSUE THREAD

**Issue by kerim** [Southpaw1496/obsidian-send-to-ghost#2]
I see that to use custom integrations in Ghost I have to upgrade from $9/month to $25/month ... I'm wondering if there is anyway this could be made to work with some of the default integrations? Both Ulysses and iA writer seem able to do it with just the API key...

**Comment by Southpaw1496** [comment]
That restriction is only for Ghost's official Ghost Pro managed hosting. If you use a different host or host Ghost yourself, it doesn't apply.

There is an alternative way of authenticating with Ghost called [User Authentication](https://ghost.org/docs/admin-api#user-authentication) (as opposed to token authentication that Send to Ghost uses), which uses the username and password, and that's what Ulysses uses. If I ever have the time to rewrite Send to Ghost, I think that's the authentication method I would use, as it seems like the easiest one for users. However, I'm not sure whether that would bypass Ghost Pro's restrictions, or whether the prebuilt integrations like Ulysses and iA Writer have something else that marks them as "official". From the wording of the Ghost Pro page on Ghost's website, I would assume this is the case, and using User Authentication would not allow you to bypass the restrictions on custom integrations like Send to Ghost.

**Comment by kerim** [comment]
Thanks for looking into it. Yes, I'm a Ghost Pro user. Neither Ulysses or iA writer are listed as standard (non-custom) integrations. I think they just use the API. If so, it should be possible to do the same thing as what they do if you ever re-write this. Thanks!

**Comment by Southpaw1496** [comment]
I have found a possible workaround, which is that you can use the Staff Access Token in your Profile settings (Ghost -> Avatar in the bottom-right -> Profile) as a drop-in replacement to the Admin API token. Can you confirm if it works with Ghost Pro?

**Comment by kerim** [comment]
That works! Thanks. The URL is just the root URL of my ghost dashboard.

https://[[site name]].ghost.io/

**Comment by Southpaw1496** [comment]
With 1.0.4, I've updated the settings screen to be more inclusive of Staff Access Tokens, and the usage instructions on the README now recommend them over creating a custom integration.
