### ISSUE TITLE
Images not being pushed.

### ISSUE THREAD

**Issue by Akhil-Theerthala** [Southpaw1496/obsidian-send-to-ghost#3]
The image files inside the note aren't being pushed into the ghost drafts.

**Comment by Southpaw1496** [comment]
I took almost all the code for this plugin from the "Obsidian Ghost Publish" plugin after it was taken off the extensions store, so that's obviously something the original author didn't add. If I ever have time to rewrite the plugin with my own code, this would be one of the features I would add.

**Comment by Akhil-Theerthala** [comment]
Oh. Ok.
